// app/layout.tsx  (RootLayout)

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/common/Provider";
import Navbar from "@/components/common/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AggTrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050C19] relative`}
        >
          {/* ───── background ───── */}
          <div className="fixed inset-0 -z-10 overflow-hidden">
            <video
              className="w-full h-full object-cover"
              src="/assets/home.mp4"
              autoPlay
              muted
              loop
              playsInline
              preload="auto"
            />
          </div>

          {/* ───── main UI ───── */}
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
