// app/layout.tsx (RootLayout)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WagmiWalletProvider from "@/components/providers/WagmiWalletProvider";
import Navbar from "@/components/common/navbar/Navbar";
import MuiThemeProvider from "@/components/providers/MuiThemeProvider";
import { ConditionalMorphoNavbar } from "@/components/common/navbar/ConditionalMorphoNavbar";
import { Toolbar } from "@mui/material";
import { ChainProvider } from "@/context/ChainContext";
import { GoogleAnalytics } from "@next/third-parties/google";
import { DerivedStateTwapProvider } from "@/store/limit-order/derivedstate-twap-provider";
import { VaultProviders } from "@/lib/yearnfi/lib/contexts/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AggTrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050C19] relative`}
      >
        <WagmiWalletProvider>
          <MuiThemeProvider>
            <ChainProvider defaultChain="ETHEREUM">
              <DerivedStateTwapProvider isLimitOrder={true}>
                <VaultProviders>
                  {/* Background */}
                  <div className="fixed inset-0 -z-10 overflow-hidden">
                    <img
                      src="/ellipse-home.png"
                      className="w-full h-full object-cover"
                      alt=""
                    />
                  </div>
                  {/* Main UI */}
                  <Navbar />
                  <ConditionalMorphoNavbar />
                  {children}
                </VaultProviders>
              </DerivedStateTwapProvider>
            </ChainProvider>
          </MuiThemeProvider>
        </WagmiWalletProvider>

        <GoogleAnalytics gaId="G-RGY5G35G2R" />
      </body>
    </html>
  );
}
