"use client";

import { Box, Typography, Divider } from "@mui/material";
import type { TYDaemonVault } from "@/lib/yearnfi/lib/utils/schemas/yDaemonVaultsSchemas";
import { formatAmount } from "@/lib/yearnfi/lib/utils";

type InfoTabProps = {
  vault: TYDaemonVault;
};

function InfoRow({
  label,
  value,
  tooltip,
}: {
  label: string;
  value: string | React.ReactNode;
  tooltip?: string;
}) {
  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        py: 2,
      }}
    >
      <Typography
        variant="body2"
        sx={{ fontWeight: 600, color: "text.secondary" }}
      >
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{ fontFamily: "monospace", fontWeight: 600 }}
        title={tooltip}
      >
        {value}
      </Typography>
    </Box>
  );
}

export function InfoTab({ vault }: InfoTabProps) {
  // Calculate some metrics
  const totalAssets = vault.tvl?.totalAssets
    ? Number(vault.tvl.totalAssets) / Math.pow(10, vault.decimals)
    : 0;

  const pricePerShare = vault.tvl?.totalAssets
    ? Number(vault.tvl.totalAssets) /
        Math.pow(10, vault.decimals) /
        totalAssets || 1
    : 1;

  return (
    <Box sx={{ display: "flex", flexDirection: "column", gap: 4 }}>
      {/* Vault Metrics */}
      <Box>
        <Typography variant="h6" sx={{ mb: 2, fontWeight: 700 }}>
          Vault Metrics
        </Typography>
        <Box
          sx={{
            bgcolor: "rgba(0, 255, 233, 0.05)",
            borderRadius: 2,
            p: 3,
            border: "1px solid",
            borderColor: "rgba(0, 255, 233, 0.2)",
          }}
        >
          <InfoRow
            label="Total Assets"
            value={`${formatAmount(totalAssets, 2, 2)} ${vault.token.symbol}`}
            tooltip={`${totalAssets} ${vault.token.symbol}`}
          />
          <Divider />
          <InfoRow
            label="Total Value Locked (TVL)"
            value={`$${formatAmount(vault.tvl?.tvl || 0, 2, 2)}`}
          />
          <Divider />
          <InfoRow
            label="Price Per Share"
            value={formatAmount(pricePerShare, 6, 6)}
            tooltip="Amount of underlying tokens per vault share"
          />
          <Divider />
          <InfoRow
            label="Token Price"
            value={`$${formatAmount(vault.tvl?.price || 0, 2, 6)}`}
          />
        </Box>
      </Box>

      {/* Fees */}
      <Box>
        <Typography variant="h6" sx={{ mb: 2, fontWeight: 700 }}>
          Fees
        </Typography>
        <Box
          sx={{
            bgcolor: "rgba(0, 255, 233, 0.05)",
            borderRadius: 2,
            p: 3,
            border: "1px solid",
            borderColor: "rgba(0, 255, 233, 0.2)",
          }}
        >
          <InfoRow
            label="Management Fee"
            value="0%"
            tooltip="Annual fee charged on assets under management"
          />
          <Divider />
          <InfoRow
            label="Performance Fee"
            value="10%"
            tooltip="Fee charged on profits generated by the vault"
          />
          <Divider />
          <InfoRow
            label="Withdrawal Fee"
            value="0%"
            tooltip="Fee charged when withdrawing from the vault"
          />
        </Box>
        <Typography
          variant="caption"
          sx={{ display: "block", mt: 1, color: "text.secondary" }}
        >
          Performance fees are only charged on profits and help maintain the
          vault's operations
        </Typography>
      </Box>

      {/* Limits & Parameters */}
      <Box>
        <Typography variant="h6" sx={{ mb: 2, fontWeight: 700 }}>
          Limits & Parameters
        </Typography>
        <Box
          sx={{
            bgcolor: "rgba(0, 255, 233, 0.05)",
            borderRadius: 2,
            p: 3,
            border: "1px solid",
            borderColor: "rgba(0, 255, 233, 0.2)",
          }}
        >
          <InfoRow
            label="Deposit Limit"
            value="Unlimited"
            tooltip="Maximum amount that can be deposited"
          />
          <Divider />
          <InfoRow
            label="Minimum Deposit"
            value={`0.01 ${vault.token.symbol}`}
            tooltip="Minimum amount required to deposit"
          />
          <Divider />
          <InfoRow
            label="Vault Status"
            value={
              <Box
                sx={{
                  px: 2,
                  py: 0.5,
                  borderRadius: 1,
                  bgcolor:
                    vault.status === "active" ? "success.main" : "warning.main",
                  color: "white",
                  fontSize: "0.75rem",
                  fontWeight: "bold",
                }}
              >
                {vault.status?.toUpperCase() || "ACTIVE"}
              </Box>
            }
          />
          <Divider />
          <InfoRow
            label="Emergency Shutdown"
            value="No"
            tooltip="Whether the vault is in emergency shutdown mode"
          />
        </Box>
      </Box>

      {/* Technical Details */}
      <Box>
        <Typography variant="h6" sx={{ mb: 2, fontWeight: 700 }}>
          Technical Details
        </Typography>
        <Box
          sx={{
            bgcolor: "rgba(0, 255, 233, 0.05)",
            borderRadius: 2,
            p: 3,
            border: "1px solid",
            borderColor: "rgba(0, 255, 233, 0.2)",
          }}
        >
          <InfoRow label="API Version" value={vault.version || "3.0.0"} />
          <Divider />
          <InfoRow label="Vault Type" value={vault.kind || "Multi Strategy"} />
          <Divider />
          <InfoRow
            label="Number of Strategies"
            value={vault.strategies?.length || 0}
          />
          <Divider />
          <InfoRow
            label="Endorsed"
            value="Yes"
            tooltip="This vault is endorsed by Yearn governance"
          />
        </Box>
      </Box>
    </Box>
  );
}
